//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionHead()
        {
            this.TransactionLine = new HashSet<TransactionLine>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int StaffID { get; set; }
        public int StoreID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLine> TransactionLine { get; set; }
    }
}
